PROYECTOFINA/app/models/clientes.py
from app import db
from sqlalchemy.orm import relationship

class  Clientes(db.Model):
    __tablename__ = 'cliente'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(255), nullable=False)
    direccion = db.Column(db.String(255), nullable=False)
    telefono = db.Column(db.String(255), nullable=False)
    correo = db.Column(db.String(255), nullable=False)
    

PROYECTOFINA/app/routes/clientes_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models.clientes import Clientes
from app import db

bp = Blueprint('clientes', __name__)

@bp.route('/')
def home():
    return render_template('home/index.html')

@bp.route('/index')
def index():
    data = Clientes.query.all()
    return render_template('clientes/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombre  = request.form['nombre']
        direccion = request.form['direccion']
        telefono = request.form['telefono']
        correo = request.form['correo']

        clientes=Clientes (nombre=nombre, direccion=direccion, telefono=telefono, correo=correo)

        db.session.add(clientes)
        db.session.commit()

        return redirect(url_for('clientes.index'))
    return render_template('clientes/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    car = Clientes.query.get_or_404(id)
    if request.method == 'POST':
        clientes.nombre = request.form['nombre']
        clientes.direccion = request.form['direccion'] 
        clientes.telefono = request.form['telefono']
        clientes.correo = request.form['correo']
        db.session.commit()
        return redirect(url_for('clientes.index'))
    
    return render_template('clientes/edit.html', clientes=clientes)

@bp.route('/delete/<int:id>')
def delete(id):
    clientes = Clientes.query.get_or_404(id)
    db.session.delete(cliente)
    db.session.commit()
    return redirect(url_for('clientes.index'))

PROYECTOFINA/app/templates/clientes/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/style.css') }}">
    <title>Agregar clientes</title>
</head>
<body>
    <h1>Agregar clientes</h1>
    <form action="{{ url_for('clientes.add') }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre"  required>
        <label for="direccion">Direccion:</label>
        <input type="text" id="direccion" name="direccion"  required>
        <label for="telefono">Telefono:</label>
        <input type="text" id="telefono" name="telefono"  required>
        <label for="correo">Correo:</label>
        <input type="text" id="correo" name="correo"  required>
        <button type="submit">Agregar cliente</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/clientes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Cliente</title>
</head>
<body>
    <h1>Editar Cliente</h1>
    <form action="{{ url_for('clientes.edit', id=clientes.id) }}" method="post">
        
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre value=" value="{{ clientes.nombre }}" required>
        <label for="direccion">Direccion:</label>
        <input type="text" id="direccion" name="direccion" value="{{ clientes.direccion }}" required>
        <label for="telefono">Telefono:</label>
        <input type="text" id="telefono" name="telefono" value="{{ clientes.telefono }}" required>
        <label for="correo">Correo:</label>
        <input type="text" id="correo" name="correo" value="{{ clientes.correo }}" required>
        <button type="submit">Actualizar clientes</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/clientes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Inventario de clientes</title>
</head>
<body>
    <h1>Lista de Clientes</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Telefono</th>
            <th>Correo</th>
            
        </tr>
        {% for clientes in data %}
            <tr>
                <td>{{ clientes.id }}</td>
                <td>{{ clientes.nombre }}</td>
                <td>{{ clientes.direccion }}</td>
                <td>{{ clientes.telefono }}</td>
                <td>{{ clientes.correo }}</td>
                <td>
                    <a href="{{ url_for('clientes.edit', id=clientes.id) }}">Editar</a>
                    <a href="{{ url_for('clientes.delete', id=clientes.id) }}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('clientes.add') }}">Agregar Clientes</a>
</body>
</html>