PROYECTOFINA/app/models/materiales.py
from app import db
from sqlalchemy.orm import relationship

class  Materiales(db.Model):
    __tablename__ = 'material'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(255), nullable=False)
    tipo = db.Column(db.String(255), nullable=False)
    costo = db.Column(db.String(255), nullable=False)
    cantidad = db.Column(db.String(255), nullable=False)

PROYECTOFINA/app/routes/compras_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models.compras import Compras
from app import db

bp = Blueprint('compras', __name__)

@bp.route('/compras')
def index():
    data = Compras.query.all()
    return render_template('compras/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        fecha  = request.form['fecha']
        total = request.form['total']
        

        compras=Compras (fecha=fecha, total=total)

        db.session.add(compras)
        db.session.commit()

        return redirect(url_for('compras.index'))
    return render_template('compras/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    car = Compras.query.get_or_404(id)
    if request.method == 'POST':
        compras.fecha = request.form['fecha']
        compras.total = request.form['total'] 
        
        db.session.commit()
        return redirect(url_for('compras.index'))
    
    return render_template('compras/edit.html', compras=compras)

@bp.route('/delete/<int:id>')
def delete(id):
    compras = Compras.query.get_or_404(id)
    db.session.delete(compras)
    db.session.commit()
    return redirect(url_for('compras.index'))

PROYECTOFINA/app/routes/materiales_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models.materiales import Materiales
from app import db

bp = Blueprint('materiales', __name__)

@bp.route('/materiales')
def index():
    data = Materiales.query.all()
    return render_template('materiales/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombre  = request.form['nombre']
        tipo = request.form['tipo']
        costo = request.form['costo']
        cantidad = request.form['cantidad']

        materiales=Materiales (nombre=nombre, tipo=tipo, costo=costo, cantidad=cantidad)

        db.session.add(materiales)
        db.session.commit()

        return redirect(url_for('materiales.index'))
    return render_template('materiales/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    car =   Materiales.query.get_or_404(id)
    if request.method == 'POST':
        materiales.nombre = request.form['nombre']
        materiales.tipo = request.form['tipo'] 
        materiales.costo = request.form['costo']
        materiales.cantidad = request.form['cantidad']
        db.session.commit()
        return redirect(url_for('materiales.index'))
    
    return render_template('materiales/edit.html', materiales=materiales)

@bp.route('/delete/<int:id>')
def delete(id):
    materiales = Materiales.query.get_or_404(id)
    db.session.delete(materiales)
    db.session.commit()
    return redirect(url_for('materiales.index'))

PROYECTOFINA/app/templates/materiales/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar materiales</title>
</head>
<body>
    <h1>Agregar materiales</h1>
    <form action="{{ url_for('compras.add') }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre"  required>
        <label for="tipo">Tipo:</label>
        <input type="text" id="tipo" name="tipo"  required>
        <label for="costo">Costo:</label>
        <input type="text" id="costo" name="costo"  required>
        <label for="cantidad">Cantidad:</label>
        <input type="text" id="cantidad" name="cantidad"  required>
        
        <button type="submit">Agregar materiales</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/materiales/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Materiales</title>
</head>
<body>
    <h1>Editar Materiales</h1>
    <form action="{{ url_for('materiales.edit', id=materiales.id) }}" method="post">
        
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre value=" value="{{ materiales.nombre }}" required>
        <label for="tipo">Tipo:</label>
        <input type="text" id="tipo" name="tipo" value="{{ materiales.tipo }}" required>
        <label for="costo">Costo:</label>
        <input type="text" id="costo" name="costo" value="{{ materiales.costo }}" required>
        <label for="cantidad">Cantidad:</label>
        <input type="text" id="cantidad" name="cantidad" value="{{ materiales.cantidad }}" required>
        <button type="submit">Actualizar materiales</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/materiales/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Inventario de materiales</title>
</head>
<body>
    <h1>Lista de Materiales</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Costo</th>
            <th>Cantidad</th>
            
        </tr>
        {% for materiales in data %}
            <tr>
                <td>{{ materiales.id }}</td>
                <td>{{ materiales.nombre }}</td>
                <td>{{ materiales.tipo }}</td>
                <td>{{ materiales.costo }}</td>
                <td>{{ materiales.cantidad }}</td>
                <td>
                    <a href="{{ url_for('materiales.edit', id=materiales.id) }}">Editar</a>
                    <a href="{{ url_for('materiales.delete', id=materiales.id) }}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('materiales.add') }}">Agregar Materiales</a>
</body>
</html>