PROYECTOFINA/app/models/muebles.py
from app import db
from sqlalchemy.orm import relationship

class  Muebles (db.Model):
    __tablename__ = 'mueble'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(255), nullable=False)
    descripcion = db.Column(db.String(255), nullable=False)
    precio = db.Column(db.String(255), nullable=False)
    cantidad = db.Column(db.String(255), nullable=False)

PROYECTOFINA/app/routes/muebles_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models.muebles import Muebles
from app import db

bp = Blueprint('muebles', __name__)

@bp.route('/muebles')
def index():
    data = Muebles.query.all()
    return render_template('muebles/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        nombre  = request.form['nombre']
        descripcion = request.form['descripcion']
        precio = request.form['precio']
        cantidad = request.form['cantidad']

        muebles=Muebles (nombre=nombre, descripcion=descripcion, precio=precio, cantidad=cantidad)

        db.session.add(muebles)
        db.session.commit()

        return redirect(url_for('muebles.index'))
    return render_template('muebles/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    car =   Muebles.query.get_or_404(id)
    if request.method == 'POST':
        muebles.nombre = request.form['nombre']
        muebles.tipo = request.form['tipo'] 
        muebles.costo = request.form['costo']
        muebles.cantidad = request.form['cantidad']
        db.session.commit()
        return redirect(url_for('muebles.index'))
    
    return render_template('muebles/edit.html', muebles=muebles)

@bp.route('/delete/<int:id>')
def delete(id):
    muebles = Muebles.query.get_or_404(id)
    db.session.delete(muebles)
    db.session.commit()
    return redirect(url_for('muebles.index'))

PROYECTOFINA/app/templates/muebles/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar muebles</title>
</head>
<body>
    <h1>Agregar muebles</h1>
    <form action="{{ url_for('muebles.add') }}" method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre"  required>
        <label for="descripcion">Descripcion:</label>
        <input type="text" id="descripcion" name="descripcion"  required>
        <label for="precio">Precio:</label>
        <input type="text" id="precio" name="precio"  required>
        <label for="cantidad">Cantidad:</label>
        <input type="text" id="cantidad" name="cantidad"  required>
        
        <button type="submit">Agregar cantidad</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/muebles/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Muebles</title>
</head>
<body>
    <h1>Editar Muebles</h1>
    <form action="{{ url_for('muebles.edit', id=muebles.id) }}" method="post">
        
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre value=" value="{{ muebles.nombre }}" required>
        <label for="descripcion">Descripcion:</label>
        <input type="text" id="descripcion" name="descripcion" value="{{ muebles.descripcion }}" required>
        <label for="precio">Precio:</label>
        <input type="text" id="precio" name="precio" value="{{ muebles.precio }}" required>
        <label for="cantidad">Cantidad:</label>
        <input type="text" id="cantidad" name="cantidad" value="{{ muebles.cantidad }}" required>
        <button type="submit">Actualizar muebles</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/muebles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Inventario de muebles</title>
</head>
<body>
    <h1>Lista de Muebles</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th>Cantidad</th>
            
        </tr>
        {% for muebles in data %}
            <tr>
                <td>{{ muebles.id }}</td>
                <td>{{ muebles.nombre }}</td>
                <td>{{ muebles.descripcion}}</td>
                <td>{{ muebles.precio }}</td>
                <td>{{ muebles.cantidad }}</td>
                <td>
                    <a href="{{ url_for('muebles.edit', id=muebles.id) }}">Editar</a>
                    <a href="{{ url_for('muebles.delete', id=muebles.id) }}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('muebles.add') }}">Agregar Muebles</a>
</body>
</html>