PROYECTOFINA/app/models/compras.py
from app import db
from sqlalchemy.orm import relationship

class  Compras(db.Model):
    __tablename__ = 'compra'
    id = db.Column(db.Integer, primary_key=True)
    fecha = db.Column(db.String(255), nullable=False)
    total = db.Column(db.String(255), nullable=False)
    id_proveedor = db.Column(db.Integer, db.ForeignKey('proveedor.id'))

PROYECTOFINA/app/routes/compras_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.models.compras import Compras
from app import db

bp = Blueprint('compras', __name__)

@bp.route('/compras')
def index():
    data = Compras.query.all()
    return render_template('compras/index.html', data=data)

@bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        fecha  = request.form['fecha']
        total = request.form['total']
        

        compras=Compras (fecha=fecha, total=total)

        db.session.add(compras)
        db.session.commit()

        return redirect(url_for('compras.index'))
    return render_template('compras/add.html')

@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    car = Compras.query.get_or_404(id)
    if request.method == 'POST':
        compras.fecha = request.form['fecha']
        compras.total = request.form['total'] 
        
        db.session.commit()
        return redirect(url_for('compras.index'))
    
    return render_template('compras/edit.html', compras=compras)

@bp.route('/delete/<int:id>')
def delete(id):
    compras = Compras.query.get_or_404(id)
    db.session.delete(compras)
    db.session.commit()
    return redirect(url_for('compras.index'))

PROYECTOFINA/app/templates/compras/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Agregar compras</title>
</head>
<body>
    <h1>Agregar compras</h1>
    <form action="{{ url_for('compras.add') }}" method="post">
        <label for="fecha">Fecha:</label>
        <input type="text" id="fecha" name="fecha"  required>
        <label for="total">Total:</label>
        <input type="text" id="total" name="total"  required>
        
        <button type="submit">Agregar compras</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/compras/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Editar Compras</title>
</head>
<body>
    <h1>Editar Compras</h1>
    <form action="{{ url_for('compras.edit', id=compras.id) }}" method="post">
        
        <label for="fecha">Fecha:</label>
        <input type="text" id="fecha" name="fecha value=" value="{{ compras.fecha }}" required>
        <label for="total">Total:</label>
        <input type="text" id="total" name="total" value="{{ compras.total }}" required>
        
        <button type="submit">Actualizar compras</button>
    </form>
</body>
</html>

PROYECTOFINA/app/templates/compras/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Inventario de Compras</title>
</head>
<body>
    <h1>Lista de Compras</h1>
    <table>
        <tr>
            <th>ID</th>
            <th>Fecha</th>
            <th>Total</th>
        
            
        </tr>
        {% for compras in data %}
            <tr>
                <td>{{ compras.id }}</td>
                <td>{{ compras.fecha }}</td>
                <td>{{ compras.total }}</td>
                <td>
                    <a href="{{ url_for('compras.edit', id=compras.id) }}">Editar</a>
                    <a href="{{ url_for('compras.delete', id=compras.id) }}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{{ url_for('compras.add') }}">Agregar Compras</a>
</body>
</html>